<h2>Section 1: Loading and preparing data for machine learning readiness</h2>

In [68]:
import numpy as np
import pandas as pd

# Data Set Information:

The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. 

There are four datasets: 
1) bank-additional-full.csv with all examples (41188) and 20 inputs, ordered by date (from May 2008 to November 2010), very close to the data analyzed in [Moro et al., 2014]
2) bank-additional.csv with 10% of the examples (4119), randomly selected from 1), and 20 inputs.
3) bank-full.csv with all examples and 17 inputs, ordered by date (older version of this dataset with less inputs). 
4) bank.csv with 10% of the examples and 17 inputs, randomly selected from 3 (older version of this dataset with less inputs). 
The smallest datasets are provided to test more computationally demanding machine learning algorithms (e.g., SVM). 

The classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).

Attribute Information:

Input variables:
# bank client data:
1 - age (numeric)
2 - job : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')
3 - marital : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)
4 - education (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')
5 - default: has credit in default? (categorical: 'no','yes','unknown')
6 - housing: has housing loan? (categorical: 'no','yes','unknown')
7 - loan: has personal loan? (categorical: 'no','yes','unknown')
# related with the last contact of the current campaign:
8 - contact: contact communication type (categorical: 'cellular','telephone') 
9 - month: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')
10 - day_of_week: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')
11 - duration: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
# other attributes:
12 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)
13 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
14 - previous: number of contacts performed before this campaign and for this client (numeric)
15 - poutcome: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')
# social and economic context attributes
16 - emp.var.rate: employment variation rate - quarterly indicator (numeric)
17 - cons.price.idx: consumer price index - monthly indicator (numeric) 
18 - cons.conf.idx: consumer confidence index - monthly indicator (numeric) 
19 - euribor3m: euribor 3 month rate - daily indicator (numeric)
20 - nr.employed: number of employees - quarterly indicator (numeric)

Output variable (desired target):
21 - y - has the client subscribed a term deposit? (binary: 'yes','no')

In [69]:
raw_data = pd.read_csv("./bank-additional/bank-additional-full.csv", sep=';')

In [70]:
raw_data.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon ...         1    999         0  nonexistent          1.1   
1   may         mon ...         1    999         0  nonexistent          1.1   
2   may         mon ...         1    999         0  nonexistent          1.1   
3   may         mon ...         1    999         0  nonexistent          1.1   
4   may         mon ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [71]:
raw_data = raw_data.drop(['duration'], axis=1)

In [72]:
original_column = raw_data.columns
full_column = pd.get_dummies(raw_data, drop_first=False).columns
test_column = pd.get_dummies(raw_data, drop_first=True).columns

In [73]:
original_column, full_column, test_column

(Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
        'contact', 'month', 'day_of_week', 'campaign', 'pdays', 'previous',
        'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx',
        'euribor3m', 'nr.employed', 'y'],
       dtype='object'),
 Index(['age', 'campaign', 'pdays', 'previous', 'emp.var.rate',
        'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed',
        'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
        'job_management', 'job_retired', 'job_self-employed', 'job_services',
        'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
        'marital_divorced', 'marital_married', 'marital_single',
        'marital_unknown', 'education_basic.4y', 'education_basic.6y',
        'education_basic.9y', 'education_high.school', 'education_illiterate',
        'education_professional.course', 'education_university.degree',
        'education_unknown', 'default_no', 'default_unknown

In [74]:
ps_data = pd.get_dummies(raw_data, drop_first=True)

In [75]:
ps_data.head()

age  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0   56         1    999         0           1.1          93.994   
1   57         1    999         0           1.1          93.994   
2   37         1    999         0           1.1          93.994   
3   40         1    999         0           1.1          93.994   
4   56         1    999         0           1.1          93.994   

   cons.conf.idx  euribor3m  nr.employed  job_blue-collar  ...    month_nov  \
0          -36.4      4.857       5191.0                0  ...            0   
1          -36.4      4.857       5191.0                0  ...            0   
2          -36.4      4.857       5191.0                0  ...            0   
3          -36.4      4.857       5191.0                0  ...            0   
4          -36.4      4.857       5191.0                0  ...            0   

   month_oct  month_sep  day_of_week_mon  day_of_week_thu  day_of_week_tue  \
0          0          0                1                0                0   
1          0          0                1                0                0   
2          0          0                1                0                0   
3          0          0                1                0                0   
4          0          0                1                0                0   

   day_of_week_wed  poutcome_nonexistent  poutcome_success  y_yes  
0                0                     1                 0      0  
1                0                     1                 0      0  
2                0                     1                 0      0  
3                0                     1                 0      0  
4                0                     1                 0      0  

[5 rows x 53 columns]

In [76]:
ps_data.tail()

age  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
41183   73         1    999         0          -1.1          94.767   
41184   46         1    999         0          -1.1          94.767   
41185   56         2    999         0          -1.1          94.767   
41186   44         1    999         0          -1.1          94.767   
41187   74         3    999         1          -1.1          94.767   

       cons.conf.idx  euribor3m  nr.employed  job_blue-collar  ...    \
41183          -50.8      1.028       4963.6                0  ...     
41184          -50.8      1.028       4963.6                1  ...     
41185          -50.8      1.028       4963.6                0  ...     
41186          -50.8      1.028       4963.6                0  ...     
41187          -50.8      1.028       4963.6                0  ...     

       month_nov  month_oct  month_sep  day_of_week_mon  day_of_week_thu  \
41183          1          0          0                0                0   
41184          1          0          0                0                0   
41185          1          0          0                0                0   
41186          1          0          0                0                0   
41187          1          0          0                0                0   

       day_of_week_tue  day_of_week_wed  poutcome_nonexistent  \
41183                0                0                     1   
41184                0                0                     1   
41185                0                0                     1   
41186                0                0                     1   
41187                0                0                     0   

       poutcome_success  y_yes  
41183                 0      1  
41184                 0      0  
41185                 0      0  
41186                 0      1  
41187                 0      0  

[5 rows x 53 columns]

In [77]:
ps_data.shape

(41188, 53)

In [78]:
ps_data[ps_data.isnull().any(axis=1)]

Empty DataFrame
Columns: [age, campaign, pdays, previous, emp.var.rate, cons.price.idx, cons.conf.idx, euribor3m, nr.employed, job_blue-collar, job_entrepreneur, job_housemaid, job_management, job_retired, job_self-employed, job_services, job_student, job_technician, job_unemployed, job_unknown, marital_married, marital_single, marital_unknown, education_basic.6y, education_basic.9y, education_high.school, education_illiterate, education_professional.course, education_university.degree, education_unknown, default_unknown, default_yes, housing_unknown, housing_yes, loan_unknown, loan_yes, contact_telephone, month_aug, month_dec, month_jul, month_jun, month_mar, month_may, month_nov, month_oct, month_sep, day_of_week_mon, day_of_week_thu, day_of_week_tue, day_of_week_wed, poutcome_nonexistent, poutcome_success, y_yes]
Index: []

[0 rows x 53 columns]

In [79]:
X = ps_data.iloc[:, :-1].values
y = ps_data['y_yes'].values

In [80]:
X, y

(array([[ 56.,   1., 999., ...,   0.,   1.,   0.],
        [ 57.,   1., 999., ...,   0.,   1.,   0.],
        [ 37.,   1., 999., ...,   0.,   1.,   0.],
        ...,
        [ 56.,   2., 999., ...,   0.,   1.,   0.],
        [ 44.,   1., 999., ...,   0.,   1.,   0.],
        [ 74.,   3., 999., ...,   0.,   0.,   0.]]),
 array([0, 0, 0, ..., 0, 1, 0], dtype=uint8))

In [81]:
X.shape, y.shape

((41188, 52), (41188,))

<h2>Section 2: Building up machine learning model, train and test the data</h2>

In [99]:
# Feature Selection
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
lsvc = LinearSVC(C=0.1, penalty = 'l2', dual=False).fit(X, y)
model = SelectFromModel(lsvc, prefit=True)
X_new = model.transform(X)
X_new.shape

(41188, 15)

In [100]:
from sklearn.model_selection import train_test_split

In [101]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size = 0.2, random_state = 0)

In [102]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((32950, 15), (8238, 15), (32950,), (8238,))

In [103]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [104]:
# Random Forest Classification.
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', max_features = 'sqrt', random_state = 0)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [105]:
# Predicting the Test set results
y_pred = rf_classifier.predict(X_test)

In [108]:
# Logistic Regression Classification
from sklearn.linear_model import LogisticRegression
lr_classifier = LogisticRegression(random_state = 0)
lr_classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [109]:
y_pred = lr_classifier.predict(X_test)

In [ ]:
# SVM Classification
from sklearn.svm import SVC
svc_classifier = SVC(kernel='linear', random_state=0)
svc_classifier.fit(X_train, y_train)

In [27]:
y_pred = svc_classifier.predict(X_test)

<h2>Section 3: Evaluating prediction performance</h2>

In [106]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
rf_cm = confusion_matrix(y_test, y_pred)

In [107]:
rf_cm

array([[7143,  176],
       [ 697,  222]], dtype=int64)

In [110]:
lr_cm = confusion_matrix(y_test, y_pred)

In [111]:
lr_cm

array([[7219,  100],
       [ 786,  133]], dtype=int64)

In [29]:
svc_cm = confusion_matrix(y_test, y_pred)
svc_cm

array([[7204,  115],
       [ 706,  213]], dtype=int64)

<h2>Section 4: Ready to process new inputs with tested prediction model......</h2>

Please provide new data based ont the same data structure. Then, we'll be able to show you the results from the predictive modeling above.